//===== sort.hpp =======================================================================================================
//
//  Author: Immanuel Haffner <haffner.immanuel@gmail.com>
//
//  Licence:
//      Copyright 2019 Immanuel Haffner
//
//      Licensed under the Apache License, Version 2.0 (the "License");
//      you may not use this file except in compliance with the License.
//      You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//      Unless required by applicable law or agreed to in writing, software
//      distributed under the License is distributed on an "AS IS" BASIS,
//      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//      See the License for the specific language governing permissions and
//      limitations under the License.
//
//  Description:
//      This file provides algorithms to sort data on disk, generated by "gensort" from the sortbenchmark.org
//      benchmarks.
//
//======================================================================================================================

#pragma once


/** Sorting algorithm from the provided example. */
void example_sort(const char *infile, const char *outfile);

/** Sort by mmap-ing the input file, sort it with STL std::sort and write it sequentially to the output file directly to
 * disk. */
void stl_sort_mmap_direct(const char *in, const char *out);

/** Sort by mmap-ing the input file, sort it with STL std::sort and write it sequentially to the output file using a
 * FILE object. */
void stl_sort_mmap_file(const char *in, const char *out);

/** Sort by mmap-ing the input file, sort it with STL std::sort and write it sequentially to the output file using a
 * std::fstream. */
void stl_sort_mmap_stream(const char *in, const char *out);

/** Like stl_sort_mmap_file, but with a custom, very large buffer. */
void stl_sort_mmap_file_custom_buffer(const char *infile, const char *outfile);

/** Like stl_sort_mmap_stream, but with a custom, very large buffer. */
void stl_sort_mmap_stream_custom_buffer(const char *in, const char *out);
